# Generated by Django 5.2.8 on 2025-11-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=140, unique=True)),
                ('subtitulo', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(max_length=300, unique=True)),
                ('nivel', models.CharField(max_length=120, unique=True)),
                ('duracion_horas', models.PositiveIntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidad', models.CharField(max_length=120, unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
